### ISSUE TITLE
Can't recive "m.presence" event.

### ISSUE THREAD

**Issue by WarHound** [matrix-org/matrix-python-sdk#102]
Hi!
I'm trying to catch user presence changes, but  i don't see this events.
I'm using 

client = MatrixClient(config.MATRIX_URL)
client.login_with_password(config.MATRIX_USER, config.MATRIX_PASSWORD)
client.add_listener(all_messages)
client.start_listener_thread()

and 

def all_messages(event):
    if event['type'] == "m.room.member":
        if event['membership'] == "join":
            print("{0} joined".format(event['content']['displayname']))
    elif event['type'] == "m.room.message":
        if event['content']['msgtype'] == "m.text":
            if event['sender'] != client.user_id:
                # room = client.join_room(event['room_id'])
                # room.update_aliases()
                # print(repr(matrix_api.get_room_state(room.room_id)))
                # print(repr(room.aliases))
                evs = matrix_api.get_room_state(event['room_id'])
                res = [e.get('content', {}).get('alias') for e in evs if e.get('content', {}).get('alias') is not None]
                send_to = parseint(res[0])
                facebook.send_message(send_to, event['content']['body'], config.FB_TOKEN)
    elif event['type'] == "m.presence":
        print('User status changed')

And this catch all events like chat messages, room join/leave but nothing about user status.
One place where i'm able to find user presence - 

matrix_api = MatrixHttpApi(config.MATRIX_URL, token)
matrix_api.sync()

Pls advice.

**Comment by GalPressman** [comment]
The formatting of this issue is _really_ hard to read..
Other than that, presence events are not supported by the client currently.
The first line of code in _sync() is `# TODO: Deal with presence`

You can access it through the api though like you stated.

**Comment by WarHound** [comment]
I see. Thanks.
