### ISSUE TITLE
Add method for calculating name to display for room

### ISSUE THREAD

**Issue by delijati** [matrix-org/matrix-python-sdk#112]
The client is missing a `calculateRoomName` function:

c++ [libmatriclient](https://github.com/Fxrh/libqmatrixclient/blob/6fdadc74c6f090689daad211159930b46a66026d/room.cpp#L788)

or js [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk/blob/master/src/models/room.js#L1153)

**Comment by delijati** [comment]
This seams to be a common operation. Should it not be implemented in the server API !? @erikjohnston

**Comment by pik** [comment]
`calculateRoomName` isn't really something defined in the spec but rather an attempt to give something user-friendly when one isn't available, would be good to have it though.

**Comment by Half-Shot** [comment]
Agreed. Could have sworn we already had something like that...

**Comment by delijati** [comment]
@Half-Shot should i create a ticket in `synapse` for it ?

**Comment by delijati** [comment]
hmm `synpase` seams to already have a [calculate_room_name](https://github.com/matrix-org/synapse/blob/9bba6ebaa903a81cd94fada114aa71e20b685adb/synapse/push/presentable_names.py#L31)

**Comment by turt2live** [comment]
There is a strong recommendation in the spec on how to calculate the room name:
http://matrix.org/docs/spec/client_server/r0.2.0.html#calculating-the-display-name-for-a-room

Although this applies more to clients, it could easily be transitioned to the server.

**Comment by non-Jedi** [comment]
Closed in #142

**Comment by delijati** [comment]
I've added some more changes in my repo:
- https://github.com/delijati/matrix-python-sdk/commit/9589e66e06c907997b8a5b78116264aa0a3a3950

**Comment by non-Jedi** [comment]
@delijati feel free to create another PR. :)
