### ISSUE TITLE
Provide full installation instructions in README.rst and describe dependencies (requests)

### ISSUE THREAD

**Issue by Matrixcoffee** [matrix-org/matrix-python-sdk#115]
`ImportError: No module named requests`

Some research suggests this is an external dependency which also needs to be installed. Clarify in the readme that this is a dependency, and how to get it.

**Comment by pik** [comment]
It's in `setup.py` `install_requires`.

**Comment by Matrixcoffee** [comment]
That's nice, but the readme also doesn't tell me I need to run setup.py. :P

**Comment by pik** [comment]
`setup.py` is a standard for python projects (https://docs.python.org/3.6/distutils/setupscript.html).

**Comment by Matrixcoffee** [comment]
The [documentation](https://docs.python.org/3.6/install/index.html#the-new-standard-distutils) specifies that installation instructions should be included:

> Additionally, the distribution will contain a setup script setup.py, and a file named README.txt or possibly just README, which should explain that building and installing the module distribution is a simple matter of running one command from a terminal:

> ```
> python setup.py install
> ```

Even if said documentation did not say so, it seems like a good idea to actually include full installation instructions.

**Comment by Half-Shot** [comment]
I agree we should make it extremely obvious. The SDK could very well be one of the first libraries a first time matrix hacker comes across and it would make sense for us to be as helpful as possible.

**Comment by SimonGn** [comment]
I am a first time Matrix Hacker/new to python. It's very non-obvious, and on top of that it's a pain to get up and running in Google App Engine. Can't you use Pip?

**Comment by non-Jedi** [comment]
I've added installation instructions to the README. Let me know if it's still unclear.
