### ISSUE TITLE
Update api endpoints using v1 to use r0 instead

### ISSUE THREAD

**Issue by non-Jedi** [matrix-org/matrix-python-sdk#124]
https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$1493422976620705zgcwk:matrix.org

**Comment by pik** [comment]
It's done here (https://github.com/matrix-org/matrix-python-sdk/pull/125/commits/c7c748257376aa71f93c829b9fc8e055ab42cf51) but I'd like to have some consensus on testing before we do this, although I can extract it out into a separate PR I suppose.
