### ISSUE TITLE
Timeout value for sync request

### ISSUE THREAD

**Issue by slipeer** [matrix-org/matrix-python-sdk#131]
According [Requests doc](http://docs.python-requests.org/en/master/user/quickstart/#timeouts) it accept timeout parameter in **seconds**.
But in [api.py#L78](https://github.com/matrix-org/matrix-python-sdk/blob/master/matrix_client/api.py#L78) to this parameter passed huge value **30000 sec = 8.3 hours** from [api.py#L63](https://github.com/matrix-org/matrix-python-sdk/blob/master/matrix_client/api.py#L63)
I think line [api.py#L78](https://github.com/matrix-org/matrix-python-sdk/blob/master/matrix_client/api.py#L78)  must be like: `"timeout": timeout_ms/1000.0`

**Comment by lugino-emeritus** [comment]
AFIAK the timeout in [api.py#L78](https://github.com/matrix-org/matrix-python-sdk/blob/master/matrix_client/api.py#L78) has nothing to do with the timeout of requests. The timeout [api.py#L78](https://github.com/matrix-org/matrix-python-sdk/blob/master/matrix_client/api.py#L78) is only passed to the matrix server.

**Comment by Matrixcoffee** [comment]
This number is only passed onto the server. It is the maximum amount of time the server will let the connection hang, if no events arrive. In a word, we're long-polling here. The value should indeed be in milliseconds. See https://matrix.org/docs/spec/client_server/r0.3.0.html#get-matrix-client-r0-sync

I think this issue can be closed.

**Comment by non-Jedi** [comment]
Very good. Thanks!
