### ISSUE TITLE
Lost connection after the IP address changes on clien side

### ISSUE THREAD

**Issue by szimszon** [matrix-org/matrix-python-sdk#141]
Hi,

I wonder if somebody could help me.

 I have a problem. I made a bot with this sdk and I run it all day.
The system is behind NAT. And after my IP address changes (by ISP) the bot never recognise it and the connection is broken I have to restart the bot. :(

**Comment by non-Jedi** [comment]
At a guess, you're probably running into #129/#131

**Comment by non-Jedi** [comment]
I'm fairly certain you're running into the issues linked above. I'm closing this issue in favor of those two. If you continue to have issues after those are closed, please open another issue. Thanks!
