### ISSUE TITLE
room.set_user_profile() breaks when logging in with bare username

### ISSUE THREAD

**Issue by Matrixcoffee** [matrix-org/matrix-python-sdk#159]
If I log in as just "Coffee", that works just fine, but `room.set_user_profile()` breaks with 404 response because it tries to PUT `*/state/m.room.member/Coffee`. This should be `*/state/m.room.member/@Coffee:matrix.org`.

**Comment by Androbin** [comment]
For clarification:
* [`client > login_with_password_no_sync`](https://github.com/matrix-org/matrix-python-sdk/blob/master/matrix_client/client.py#L213) puts `username = Coffee` in a dictionary
* [`api > login`](https://github.com/matrix-org/matrix-python-sdk/blob/master/matrix_client/api.py#L150) sends that plain value to the server
* The server handles the "bare" username
* The server returns [`user_id`](https://github.com/matrix-org/matrix-python-sdk/blob/master/matrix_client/client.py#L215)` = @Coffee:matrix.org`

[`set_membership`](https://github.com/matrix-org/matrix-python-sdk/blob/master/matrix_client/api.py#L513
) fails because `user_id` was mistakenly set to `Coffee`, not `@Coffee:matrix.org`

Right so far?

**Comment by agunnik** [comment]
will this issue be fixed by appending `:matrix.org` and an '@' at the beginning to such bare usernames within [`login_with_password_no_sync`](https://github.com/matrix-org/matrix-python-sdk/blob/master/matrix_client/client.py#L213) ?

**Comment by Matrixcoffee** [comment]
@agunnik No, because the user may have their account on a server other than matrix.org.

If @Androbin is right and the server gives us the full user_id, the correct solution is to use that.

**Comment by aroneiermann** [comment]
It seems to me that this issue is fixed.

The following code works in the master branch just fine.
```python
from matrix_client.client import MatrixClient
client = MatrixClient("REDACTED")
client.login_with_password_no_sync(username="dev03", password="REDACTED")
print(client.user_id) # @dev03:REDACTED
room = client.create_room("my_room4")
room.set_user_profile(displayname="Hello World!")
```

**Comment by Matrixcoffee** [comment]
Indeed, reviewing the code, that code path wasn't broken. It does happen when you instantiate MatrixClient with a bare user_id and token. Apologies for using bad wording.

The documentation for the MatrixClient constructor was updated (e06a21d6431e75cfbccbb806d19078955a953941) around the time I created this issue, and clarifies that we need to persist the user_id we got from a previous login. It seems I missed this because I remember the previous documentation. So I think this documentation update alone closes this issue.

However, maybe the constructor could throw an exception if the user_id does not contain a colon, so the user is informed of their mistake immediately, rather than having weird errors happen somewhere down the line.

**Comment by non-Jedi** [comment]
I like @Matrixcoffee suggestion on this one since we've seen at least one person run into this bug already. Changing this to an enhancement in light of that (should only be a couple loc to fix).

**Comment by Androbin** [comment]
> maybe the constructor could throw an exception if the `user_id` does not contain a colon

The `Room` and `User` constructors already have such sanity checks.
I will simply copy the `user_id` check from `User` to `MatrixClient`.

**Comment by Androbin** [comment]
Or maybe we should put that in separate file, e.g. `checks.py` and call that from API entry points?

**Comment by Androbin** [comment]
On it. But  e.g. the `room_id` and `user_id` checks have multiple checks with different "descriptive exceptions" and the error messages shouldn't be duplicated either.
Let's continue on #205.
