### ISSUE TITLE
Exception when retrieving user avatar

### ISSUE THREAD

**Issue by DylanVanAssche** [matrix-org/matrix-python-sdk#200]
I'm trying to build a Matrix app and I want to use the rooms members their avatars in the app, the SDK fails to retrieve them.

1. **What was supposed to happen?**
When you have a `user` object you can call `get_avatar_url()` to retrieve the avatar url.

2. **What really happens:**
As soon as you call `get_avatar_url()` the following exception is raised:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/matrix_client/user.py", line 41, in get_avatar_url
    url = self.api.get_download_url(mxcurl)
  File "/usr/lib/python3.4/site-packages/matrix_client/api.py", line 715, in get_download_url
    if mxcurl.startswith('mxc://'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

3. **How to reproduce**

    1. Get an user object from a room object, user profile, ...
    2. call the `get_avatar_url()` method
    3. Exception is raised

4. **Environment**

- Python 3.4.6
- OpenSUSE LEAP 42.3 x64
- matrix_client version 0.2.0 (downloaded with PIP)

**Comment by Half-Shot** [comment]
This can happen if the user hasn't got an avatar, as it will default to None. I suggest doing a None check in user.get_avatar_url before trying to fetch it.

**Comment by DylanVanAssche** [comment]
I didn't know that! Thanks for the information!

**Comment by DylanVanAssche** [comment]
Added PR #202 to fix this :)
