### ISSUE TITLE
Run tests again python 3.7

### ISSUE THREAD

**Issue by non-Jedi** [matrix-org/matrix-python-sdk#250]
3.7 was released in late June. We should run tests against it like we do all the other python 3 versions. Is 3.4 deprecated yet? If so, we should remove testing for it.

**Comment by slipeer** [comment]
Seems that 3.4 not deprecated yet https://www.python.org/dev/peps/pep-0429/

**Comment by non-Jedi** [comment]
Per #262, we'll probably be removing support for 3.4 anyway unless some new objections come through.
