### ISSUE TITLE
user.get_display_name returns 404 Error

### ISSUE THREAD

**Issue by abhishekkumar2718** [matrix-org/matrix-python-sdk#257]
I have created a user, and when I try to access his display name, it returns 404 Error : No row found. But I haven't directly manipulated the database in anyway. I will not be able to reproduce it as I found about this by mistake.

**Comment by Zil0** [comment]
You're right, there is definitely missing exception handling there. I think it should return `None` or `''` when a user has no display name.

**Comment by non-Jedi** [comment]
Closed by #259
