### ISSUE TITLE
vector.im url path

### ISSUE THREAD

**Issue by RickCogley** [matrix-org/matrix-python-sdk#26]
Hello - thank you for creating this. I am trying to connect to vector.im, and assuming that is possible, I am not sure what the url path should be. I tried `https://vector.im/` and `https://vector.im/beta`, but neither works. Do I need a port? 

https://gist.github.com/RickCogley/36f61898b719738b65a93313c085e125

Could you please advise also: 

* is there a way to store the parameters server, username etc in a config file? 

As a goal: I would like to run a single non-interactive command on my server, to capture a log of work performed, to a given room. 

Thanks in advance for any advice you can provide. 
Sincerely,
Rick

**Comment by Half-Shot** [comment]
> I am not sure what the url path should be. I tried `https://vector.im/` and `https://vector.im/beta`, but neither works. Do I need a port? 

Hi. Currently we don't have a vector.im homeserver running, so you need to use https://matrix.org instead. 

>is there a way to store the parameters server, username etc in a config file? 

https://docs.python.org/3.5/library/configparser.html

I'd use this module as it's pretty non-trivial. In the interest of keeping things light, we don't have a config file system in the SDK itself but writing one is trivial.

Hopefully that clears everything up for you.

**Comment by RickCogley** [comment]
It does, thanks a bunch, Will! @Half-Shot
