### ISSUE TITLE
Simple example to call my bot

### ISSUE THREAD

**Issue by n1ghthunt3r** [matrix-org/matrix-python-sdk#285]
Anybody has an example of code (something very simple) so I can study? I can't start with complex things, I'm newbie in programming and these big codes kind of mess everything in my head lol. I'm trying to create a simple code where user call the bot on the room using a simple command, for example:  /botname and the bot answer with "hello user xxxx". I'm trying to do in python but something very, very simple but no success until now. 

Thanks in advance.

**Comment by Evidlo** [comment]
Just replace line 30 [here](https://github.com/matrix-org/matrix-python-sdk/blob/master/samples/SimpleChatClient.py#L30) with something like:

``` python
if event['content']['body'].startswith('/botname'):
    room.send_message("hello user " + event['sender'])
```

In the future, use the [matrix-python-sdk room](https://matrix.to/#/%23matrix-python-sdk:matrix.org) for support questions.

**Comment by n1ghthunt3r** [comment]
thanks
