### ISSUE TITLE
Can i get a list of all active monthly users ?

### ISSUE THREAD

**Issue by AyoubGhaddab** [matrix-org/matrix-python-sdk#310]
Hi, i am fairly new in the matrix ecosystem.
Is there a way to get a list of all active users from local synapse server ?

**Comment by non-Jedi** [comment]
You'll have to query the synapse database for that. I recommend asking in [#synapse:matrix.org](https://matrix.to/#/!mjbDjyNsRXndKLkHIe:matrix.org?via=matrix.org&via=privacytools.io&via=perthchat.org) or possibly [#matrix:matrix.org](https://matrix.to/#/!mjbDjyNsRXndKLkHIe:matrix.org?via=matrix.org)
