### ISSUE TITLE
Store refresh_token

### ISSUE THREAD

**Issue by gergelypolonkai** [matrix-org/matrix-python-sdk#42]
There was a discussion about the refresh token a few weeks (months?) on #matrix-dev. Yet, this SDK doesn’t store it anywhere. I think that should be a good idea (although I don’t know if it is actually handy for any current application).

**Comment by Half-Shot** [comment]
We should expose it if we don't already and make some attempt to reauth once our tokens expire.

**Comment by gergelypolonkai** [comment]
The register/login methods don't process the refresh field of the response. Also `grep refresh` gave me 0 matches on the source code.

I have a patch for this, but it modifies the API as I returned an (auth token, refresh token) tuple in the login and register methods, besides storing it in the API object.

**Comment by non-Jedi** [comment]
As far as I know, the concept of refresh tokens has been removed from the spec. If it's still there, please link me to it, and I'll reopen this issue. No clients use them, though.
