### ISSUE TITLE
client.add_listener does nothing

### ISSUE THREAD

**Issue by gufogio** [matrix-org/matrix-python-sdk#43]
Since pull request #32 was merged, `client._sync` does not notify listeners registered on the client, but only those registered on the related room.

I personally find this behavior a little counter-intuitive.

There are two solutions:
 - remove/deprecate `client.add_listener` (to make clear that it won't work)
 - make `client._sync` notify listeners on the client for every event

I would be very happy to submit a pull request after we decide what's better. Thanks :)

**Comment by dovf** [comment]
(@gufogio -- if you feel that this is hijacking your issue, just say so and we can move the discussion elsewhere)

I've been thinking a bit over the last few weeks about how to handle listeners (see also the discussion at https://matrix.to/#/#matrix-dev:matrix.org/$147188725456657vnsiX:matrix.org), and I haven't been able to come up with a good way to do it: there are so many different ways to divide the events up into groups that one may want to listen to. For example, currently per-room and per-client listeners are supported (modulo this bug report); the docstring ("Incoming event callbacks") seems to also indicate per-user listeners. However, the current implementation only covers timeline events, but not state events, so we may want to have state-event listeners, too -- and that for each of the above categories, possibly. It quickly becomes quite a mess, with lots of each-slightly-different "add_listener" APIs to support; I also suspect that we'll quickly start receiving each event multiple times -- once in each listener -- which may or may not be the desired behavior.

Does this problem resonate with anyone, or am I the only one who sees it as an issue? (Part of my problem is that I haven't actually seen any examples of code that *uses* the SDK, I've only been looking at the SDK itself, so I don't have an appreciation for how the listeners are actually used.)

Any thoughts on this?

**Comment by gufogio** [comment]
(@dovf no problem :smile:)

I am currently using the SDK for a bot-like system. Application services are a bit overkill for what I am trying to do, I don't want the hassle of setting up my server.

I find the capability to listen to all of the events on my client very useful, so I can keep track of many rooms without subscribing to each. I think that we should bring back the old behaviour of `client.add_listener'.

> However, the current implementation only covers timeline events, but not state events, so we may want to have state-event listeners, too -- and that for each of the above categories, possibly. It quickly becomes quite a mess, with lots of each-slightly-different "add_listener" APIs to support; I also suspect that we'll quickly start receiving each event multiple times -- once in each listener -- which may or may not be the desired behavior.

I don't think that's a problem because handlers can differentiate between events through `type` field. Every client-registered handler should get called for every event (including state events), every room-registered handler should get called for every room-related event. Basing on the `type`, handlers decide whether to actually *handle* the event, and how.

I find that behavior pretty simple and intuitive, but we could be more granular adding arguments to the two `add_listener` functions (like `event_type='m.room.message'` or `event_family='state'`)

**Comment by Half-Shot** [comment]
Happy with #44 for keeping old functionality.

Now, onto the other issues:
> there are so many different ways to divide the events up into groups that one may want to listen to. For example, currently per-room and per-client listeners are supported (modulo this bug report); the docstring ("Incoming event callbacks") seems to also indicate per-user listeners.

Regrettably, we do not have per user listeners. Users are 'fun' because we can either have profile wide changes or room wide changes to them (via m.room.member events which usually but not always are global changes, so context is everything!) . 

> I find that behaviour pretty simple and intuitive, but we could be more granular adding arguments to the two add_listener functions (like event_type='m.room.message' or event_family='state')

I like this. It might be the best way to do it because I think specific *functions* for each type is ridiculous. Potentially you might want to add a few wrappers for things like topic, but I'm not fussed. Event family is probably overkill, ``add_state_listener`` and ``add_listener`` would be quite fine. I also would add an option for exclusivity if people want it.

**Comment by Half-Shot** [comment]
I'm going to close this for now since the initial issue was fixed. I'll pull this onto a new issue.
