### ISSUE TITLE
Invites and kicks are not notified to listeners

### ISSUE THREAD

**Issue by gufogio** [matrix-org/matrix-python-sdk#45]
We notify only events in `response['rooms']['join']`, but there are also `response['rooms']['invite']` and `response['rooms']['leave']`. See code at https://github.com/matrix-org/matrix-python-sdk/blob/0f0c281d267a554de8fe1ddfc55dbb8ce763e447/matrix_client/client.py#L304

**Comment by gufogio** [comment]
Also, there's no way to access `ephemeral` events, like `m.receipts`.

**Comment by Half-Shot** [comment]
I've written a PR to address your first problem. I'll file a new Issue for the ephemeral data.
