### ISSUE TITLE
Redesign message sending

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-python-sdk#48]
Incrementing txn_id from 0 is not a great idea, and we should be retrying messages rather than ignoring them. Investigate options around queuing

**Comment by gergelypolonkai** [comment]
How about using an UUID?

**Comment by mweinelt** [comment]
other option: `int(time.time()*1000)`

**Comment by Half-Shot** [comment]
Probably going with

> ``int(time.time()*1000)``

just because it seems the most simple and effective way.

The harder question is this means we have to either
* Block the client during retries
* Have a background thread for MatrixAPI

**Comment by richvdh** [comment]
general recommendation for txids is "timestamp" + "counter", fwiw
