### ISSUE TITLE
Letsencrypt SSL problem

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix-python-sdk#79]
First of all: I get on an valid Letsencrypt Cert an SSL Verify Error when trying to connect.
Second Problem is after disabling the Verify is following:

```
22:51:22 INFO urllib3.connectionpool: Starting new HTTPS connection (1): matrix.ffslfl.net
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:732: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
22:51:22 INFO urllib3.connectionpool: Starting new HTTPS connection (1): matrix.ffslfl.net
22:51:23 ERROR plugins: EXCEPTION during plugin init: plugins.matrixsync
Traceback (most recent call last):
  File "/home/marcel/hangoutsbot/hangupsbot/plugins/__init__.py", line 359, in load
    the_function(bot)
  File "/home/marcel/hangoutsbot/hangupsbot/plugins/matrixsync/__init__.py", line 43, in _initialise
    matrix_bot.login_with_password(matrixsync_config['username'], matrixsync_config['password'])
  File "/usr/local/lib/python3.4/dist-packages/matrix_client/client.py", line 154, in login_with_password
    self._sync()
  File "/usr/local/lib/python3.4/dist-packages/matrix_client/client.py", line 337, in _sync
    self.sync_token = response["next_batch"]
KeyError: 'next_batch'
```

matrix_bot is initiliased with: `matrix_bot = MatrixClient("https://matrix.ffslfl.net/_matrix/client/api/v1/login?", valid_cert_check=False)`
matrixsync_config is just an array with the strings in it.

**Comment by MTRNord** [comment]
Ok the second (KeyError) got I fixed by removing `/_matrix/client/api/v1/login?` the SSL bug still is there

**Comment by Half-Shot** [comment]
~~Looks like the sync is coming out with something unexpected which is concerning.~~

Oh, yeah you fixed that. As far as the SSL bug goes, I'm not sure what you mean? If it has a verify error when trying to validate your cert then your system doesn't trust the certificate for whatever reason which isn't down to the SDK.

**Comment by MTRNord** [comment]
Yes is a validation error message. Maybe it is/was related to my Debian Version. Is Python checking against the system ca-certificates package or does Python have it's one DB?

**Comment by SShrike** [comment]
Requests (which is the HTTP library used by the Python SDK) uses it's own certificates package, which is called [Certifi](https://certifi.io/en/latest/).

**Comment by MTRNord** [comment]
I will try that. thanks for awnser
