### ISSUE TITLE
Messages are sent unencrypted?

### ISSUE THREAD

**Issue by jivank** [matrix-org/matrix-python-sdk#87]
Is there a way to configure the encryption? In the Riot app, messages sent via Python show a unlocked symbol.

**Comment by Half-Shot** [comment]
Encryption is planned in the long term, but it is a big big task. We currently do not support it in any form.
Encryption is big enough that we need to wrap around/write the encryption module used for Riot in Python which is a project all of it's own.

**Comment by Half-Shot** [comment]
Issue is being tracked #100

**Comment by pik** [comment]
Meanwhile might be worth parsing whether `m.room.encryption` and logging a warning when sending plaintext (or something of the sort)?
