### ISSUE TITLE
Add method to send HTML-formatted messages

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-python-sdk#88]
As discussed at and around https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$1483970675924545nrAds:matrix.org, it would be helpful to add a method to the `Room` class for sending HTML-formatted messages.

Putting

```python
def send_html(self, html):
    self.client.api.send_message_event(room_id, "m.room.message", self.client.api.get_html_body(html))
```

into `room.py` reportedly works

**Comment by GalPressman** [comment]
Seems like everything is already set up for this one 😃.
I'll start working on it if no one else intends to.

**Comment by xsteadfastx** [comment]
:+1:

**Comment by enckse** [comment]
consumed and started using the change with this - very awesome

**Comment by Half-Shot** [comment]
Got merged, so I'll go ahead and close it.
