### ISSUE TITLE
Can i get list of users? 

### ISSUE THREAD

**Issue by WarHound** [matrix-org/matrix-python-sdk#99]
Hi!
Can i get list of existing users from local synapse server ? Something like getUsers() from js sdk ?

**Comment by Half-Shot** [comment]
Could you clarify if you want to get a list of users *from a room* or on the server itself.
If it's the latter, I don't know of an API that does that. If it's the former then yeah, that should be doable.

**Comment by Half-Shot** [comment]
Oh, ``Room.get_joined_members()`` will get you the list of members which you can then filter for your own server if you like.

**Comment by WarHound** [comment]
Not from room. From server. Method getUsers from matrix-js-sdk return an array with all users from server. M b it's aggregated somehow from all rooms or something like this i don't know. 
I need to get a list of users, that registered on server. I'm using synapse server without sydent. So all users was added from shell.

**Comment by Half-Shot** [comment]
[getUsers](https://matrix-org.github.io/matrix-js-sdk/0.7.5/module-client-MatrixClient.html#getUsers) returns an array of all known users, not limited to your server (unless of course your user has never visited a federated room). 

In any case, to do this you just need to call ``get_joined_members()`` for each room in ``client.get_rooms()`` and remove the duplicate entries. I'm not sure if I really want to add this as a function for the SDK though, as I don't think it adds anything substantially new.

**Comment by WarHound** [comment]
I see. I just trying to find out how it's implemented in JS sdk and find only declaration but not how it's collect all users to this array. 
And what if user do not invited to any room? Or user my user do not invited to room with some users ?
